version: 2.0

# .service_defaults: &service_defaults
#   docker:
#     - image: circleci/node:8
#     - image: postgres:10.5-alpine
#       environment:
#         POSTGRES_USER: postgres
#         POSTGRES_DB: monarch_test
#   working_directory: ~/monarch

# .attach_server_workspace: &attach_server_workspace
#   attach_workspace:
#     at: ~/monarch

jobs:
  # build_service:
  #   <<: *service_defaults
  #   steps:
  #     - checkout
  #
  #     - restore_cache:
  #         keys:
  #           - v1-service-node-deps-{{ checksum "yarn.lock" }}
  #           - v1-service-node-deps-
  #
  #     - run: yarn
  #     - run: yarn gen-keys
  #
  #     - save_cache:
  #         key: v1-service-node-deps-{{ checksum "yarn.lock" }}
  #         paths:
  #           - node_modules
  #
  #     - persist_to_workspace:
  #         root: ~/monarch
  #         paths:
  #           - node_modules
  #           - rsa-private.pem
  #           - rsa-public.pem
  #
  #
  # lint_and_unit_test_service:
  #   <<: *service_defaults
  #   steps:
  #     - *attach_server_workspace
  #     - run: yarn lint
  #     - run: yarn test:unit
  #
  # feature_test_service:
  #   <<: *service_defaults
  #   steps:
  #     - *attach_server_workspace
  #     - run: yarn features

  build_and_test_ui:
    docker:
      - image: circleci/node:8
    working_directory: ~/monarch
    steps:
      - checkout

      - run: echo "BUTTS" && pwd && ls -la

      - restore_cache:
          keys:
            - v1-ui-node-deps-{{ checksum "ui/yarn.lock" }}
            - v1-ui-node-deps-

      - run:
          command: yarn
          working_directory: ~/monarch/ui

      - run:
          command: yarn lint
          working_directory: ~/monarch/ui

      - run:
          command: yarn test
          working_directory: ~/monarch/ui

      - save_cache:
          key: v1-ui-node-deps-{{ checksum "ui/yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_ui
      # - build_service
      # - lint_and_unit_test_service:
      #     requires:
      #       - build_service
      # - feature_test_service:
      #     requires:
      #       - build_service
