version: 2.0

.service_defaults: &service_defaults
  docker:
    - image: circleci/node:8
  working_directory: /root/service

.ui_defaults: &ui_defaults
  docker:
    - image: circleci/node:8
  working_directory: /root/ui

.persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: /workspace
    paths:
      - node_modules

.attach_workspace: &attach_workspace
  attach_workspace:
    at: /workspace

jobs:
  build_service:
    <<: *service_defaults
    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-service-node-deps-{{ checksum "yarn.lock" }}
            - v1-service-node-deps-

      - run:
          name: Install packages
          command: yarn

      - save_cache:
          name: Save node_modules cache
          key:
            - v1-service-node-deps-{{ checksum "yarn.lock" }}
            - v1-service-node-deps-
          paths:
          - node_modules

      - *persist_to_workspace

  lint_and_unit_test_service:
    <<: *service_defaults
    - *attach_workspace
    - run: yarn lint
    - run: yarn test:unit

  feature_test_service:
    <<: *service_defaults
    - *attach_workspace
    - run: yarn features

  build_and_test_ui:
    docker:
      - image: circleci/node:8
    working_directory: /root/ui
    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-ui-node-deps-{{ checksum "yarn.lock" }}
            - v1-ui-node-deps-

      - run: yarn
      - run: yarn lint
      - run: yarn test

      - save_cache:
          name: Save node_modules cache
          key:
            - v1-ui-node-deps-{{ checksum "yarn.lock" }}
            - v1-ui-node-deps-
          paths:
          - node_modules



workflows:
  version: 2
  build_and_test_service:
    jobs:
      - build_and_test_ui
      - build_service
      - lint_and_unit_test_service:
          requires:
            - build_service
      - feature_test_service:
          requires:
            - build_service
