version: 2.0

.service_defaults: &service_defaults
  docker:
    - image: circleci/node:8
    - image: circleci/postgres:8
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: monarch_test
  working_directory: /root/service

.attach_server_workspace: &attach_server_workspace
  attach_workspace:
    at: /root/service

jobs:
  build_service:
    <<: *service_defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-service-node-deps-{{ checksum "yarn.lock" }}
            - v1-service-node-deps-

      - run: yarn
      - run: yarn gen-keys

      - save_cache:
          key: v1-service-node-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - persist_to_workspace:
        root: /root/service
        paths:
          - node_modules
          - rsa-private.pem
          - rsa-public.pem


  lint_and_unit_test_service:
    <<: *service_defaults
    steps:
      - *attach_server_workspace
      - run: yarn lint
      - run: yarn test:unit

  feature_test_service:
    <<: *service_defaults
    steps:
      - *attach_server_workspace
      - run: yarn features

  build_and_test_ui:
    docker:
      - image: circleci/node:8
    working_directory: /root/ui
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-ui-node-deps-{{ checksum "yarn.lock" }}
            - v1-ui-node-deps-

      - run: yarn
      - run: yarn lint
      - run: yarn test

      - save_cache:
          key: v1-ui-node-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_and_test_service:
    jobs:
      - build_and_test_ui
      - build_service
      - lint_and_unit_test_service:
          requires:
            - build_service
      - feature_test_service:
          requires:
            - build_service
