version: '3'

services:
  monarch:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - postgres
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres@postgres:5432/monarch_test

  postgres:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: monarch_test
