export default {
  Api: {CALL: 'api/CALL'},
  Identity: {
    LOGIN_REQUEST: 'identity/LOGIN_REQUEST',
    LOGIN_FAILURE: 'identity/LOGIN_FAILURE',
    LOGIN_SUCCESS: 'identity/LOGIN_SUCCESS',
    UPDATE_PROFILE_REQUEST: 'identity/UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_FAILURE: 'identity/UPDATE_PROFILE_FAILURE',
    UPDATE_PROFILE_SUCCESS: 'identity/UPDATE_PROFILE_SUCCESS'
  }
};
