FROM node:carbon

WORKDIR /usr/src/api

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

ENV PATH="/root/.yarn/bin:${PATH}"

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn gen-keys

EXPOSE 8080 8081

